### ISSUE TITLE
Question: Can you also make an exe-file as release?

### ISSUE THREAD

**Issue by hutje** [lonkaars/obs-launchpad#1]
I don't know a lot about node.js, but want to use this program to be able to switch with the AKAI APCmini on OBS.

**Comment by lonkaars** [comment]
I can't test the executable because I borrowed a launchpad from someone, so I'm not putting this in the releases section. If it doesn't work you can reopen this issue and I'll reply with some running instructions.

[obs-launchpad-win.zip](https://github.com/lonkaars/obs-launchpad/files/4479515/obs-launchpad-win.zip)
